baseURL = 'https://hugo-rosie.vercel.app/'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'coHub'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Showcase"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Why Choose Us?"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "Updates"
  url= "#blog"
  weight = 4
  [[menu.Main]]
  name = "Pricing"
  url= "#pricing"
  weight = 5
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Booking"
  url= "/booking/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} Rosie & Company Inc."
  formspreeURL = "https://formspree.io/mbjwlead"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo1.png"
  footerlogo = "images/logo1.png"
  footerDescription = "Rosie's Maid Cleaning Service"

  [params.address]
  address = "2 Elm Ave. <br>  Toronto, ON M4W 1N4"
  email = "rosieandcompany@gmail.com"
  openingDesc = "You can book with our online form, but you can also just give us a call directly."
  openingHours = "We are available from 7am — 7pm week days."
  phone = "(123) 456-7890"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "43.674324"
  longitude = "-79.381848"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-dribbble"
  url = "https://dribbble.com/"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 4
  
  